### ISSUE TITLE
样式调整

### ISSUE THREAD

**Issue by tuhaihe** [CSDN-Geek/Firefox-Extension-A#3]
* 推荐标题、网址链接以及推荐理由输入框下面的横向滚动条去掉，可以增加整个弹出层的宽度
* ”发布“按钮居中

<img src="http://img.blog.csdn.net/20150921185104276">

**Comment by wusuopu** [comment]
现在的样式：

![screen shot 2015-10-03 at 12 17 14 pm](https://cloud.githubusercontent.com/assets/1478284/10261416/09848c12-69c9-11e5-858d-6b78e4e1c074.png)

**Comment by tuhaihe** [comment]
改的挺好~
